# Generated by Django 4.1.3 on 2023-01-30 04:06

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_email_alter_profile_name_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='end_time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='start_time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
    ]
