# Generated by Django 4.1.3 on 2023-01-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assessment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='end_time',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='start_time',
            field=models.CharField(max_length=256),
        ),
    ]
